#!/bin/bash

# Get the remote location
origin="$(git remote)"
# Get the primary branch
primary_branch_name="$(git remote show $origin | sed -n '/HEAD branch/s/.*: //p')"

# Return to the primary/base branch
# TOTO: allow the user to input a new base branch somehow?
git checkout "$primary_branch_name"
git pull

if [ "$1" == "$primary_branch_name" ]; then
  echo "requested branch is the primary branch... skipping"
elif [ "$#" -gt 0 ]; then
    echo "The script was called with at least one parameter. $1"
    git branch -a >> branches.txt
    if grep -Fxq "$1" "branches.txt"; then
      git checkout "$1"
    else
      git checkout -b "$1"
    fi
    rm branches.txt
fi
