#!/bin/bash

# Check if we are dealing with the help flag.
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo "Pushes the current branch up to the server. Will push the branch up even if it isn't already on the server."
  echo "No parameters."
  echo ""
  exit 0
fi

git pull

# Try to send the code to the server
if ! git push --force; then
  # The branch doesn't exist on the server
  # Send the branch up to the server
  origin="$(git remote)"
  current_branch="$(git rev-parse --abbrev-ref HEAD)"
  git push --set-upstream "$origin" "$current_branch"

  # Need to construct the url in order to open a comparison in the browser
  initial_url=$(git remote get-url "$origin" 2>/dev/null)

  if [ -z "$initial_url" ]; then
    echo "Error: Remote '$origin' not found or not in a Git repository." >&2
    exit 1
  fi

  http_substring=$(echo "$initial_url" | cut -c 1-8)
  git_substring=$(echo "$initial_url" | cut -c 1-4)
  if [ "$http_substring" = "https://" ]; then
    base_https_url="$initial_url"
  elif [ "$git_substring" = "git@" ]; then
    # Need to swap git out for https
    url_minus_git=$(echo "$initial_url" | sed 's/git@//' | sed 's/:/\//' | sed 's/\.git//')
    base_https_url="https://${url_minus_git}"
  fi

  primary_branch="$(git remote show $origin | sed -n '/HEAD branch/s/.*: //p')"
  current_branch="$(git rev-parse --abbrev-ref HEAD)"

  comparison_url="$base_https_url/compare/$primary_branch...$current_branch"
  open "$comparison_url" > /dev/null
fi