#!/bin/bash

git pull

if ! git push; then
  origin="$(git remote)"
  current_branch="$(git rev-parse --abbrev-ref HEAD)"
  git push --set-upstream "$origin" "$current_branch"

  initial_url=$(git remote get-url "$origin" 2>/dev/null)

  if [ -z "$initial_url" ]; then
    echo "Error: Remote '$origin' not found or not in a Git repository." >&2
    exit 1
  fi

  http_substring=$(echo "$initial_url" | cut -c 1-8)
  git_substring=$(echo "$initial_url" | cut -c 1-4)
  if [ "$http_substring" = "https://" ]; then
    base_https_url="$initial_url"
  elif [ "$git_substring" = "git@" ]; then
    HTTP_URL=$(echo "$initial_url" | sed 's/git@//' | sed 's/:/\//' | sed 's/\.git//')
    base_https_url="https://${HTTP_URL}"
  fi

  primary_branch="$(git remote show $origin | sed -n '/HEAD branch/s/.*: //p')"
  current_branch="$(git rev-parse --abbrev-ref HEAD)"

  comparison_url="$base_https_url/compare/$primary_branch...$current_branch"
  xdg-open "$comparison_url"
fi
